name: flutter_todo_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.3
  get_it: ^7.6.4
  bloc: ^8.1.2
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.0.0

flutter:
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
